brew "clang-format"
brew "direnv"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "git-delta"
brew "jq"
brew "lazygit"
brew "mpv"
brew "neovim", args: ["HEAD"]  # until 0.12 released
brew "nixfmt"
brew "prettier"
brew "ripgrep"
brew "ruff"
brew "shfmt"
brew "stylua"
brew "tlrc"
brew "tree-sitter-cli"
cask "claude-code"

if OS.mac?
  cask "signal"
  cask "spotify"
  cask "wezterm"
end
